 CREATE TABLE IF NOT EXISTS userAccount(
 id TINYINT UNSIGNED AUTO_INCREMENT KEY,
 username VARCHAR(20) NOT NULL UNIQUE,
 money DECIMAL(10,2)
 ) ENGINE = INNODB;
 
 

DELIMITER //
CREATE PROCEDURE test1()
BEGIN
SELECT * FROM user;
SELECT * FROM useraccount;
END
//

DELIMITER ;

CREATE TABLE test2(
id INT
);